### ISSUE TITLE
Certifying / Signing other keys

### ISSUE THREAD

**Issue by mwilck** [drduh/YubiKey-Guide#143]
Hi, I have the following question:

I can't sign other keys (other people's or my own) with the key generated following this procedure. 

    gpg  --sign-key 70700BF2

     Are you sure that you want to sign this key with your
     key "Martin Wilck <martin.wilck@suse.com>" (67C586E685569754)
    
     Really sign? (y/N) y
     gpg: signing failed: No secret key

I guess this is because only the master key has the "certify" capability. So, in order to create any signatures for keys, I would need to copy them to a stick, start my ephemeral environment with the master key, import / sign / export the other keys there, and re-import the the public keys into the normal work environment. Right?

**Comment by AlexanderBartash** [comment]
Correct @mwilck

**Comment by mwilck** [comment]
... might be worth mentioning that in the guide, then... it makes the "web of trust" maintenance  pretty cumbersome.
However, given the late signing attacks, that part of PGP is pretty much dead anyway I suppose.

**Comment by AlexanderBartash** [comment]
Well, keeping something secure is a full time job nowadays. It is all about balance. You need to choose the right level of security.

**Comment by mwilck** [comment]
Don't get me wrong, your walkthrough was extremely helpful, thanks a lot for it. I was just missing that one little piece of information (seems to be lacking elsewhere, too).

**Comment by AlexanderBartash** [comment]
It is not my repository. It is a collective effort of many people. But yes, I agree. It took me a while to figure this out myself too. Here is a good resource https://incenp.org/notes/2015/using-an-offline-gnupg-master-key.html

**Comment by netflash** [comment]
@mwilck can you please expand your comment `However, given the late signing attacks, that part of PGP is pretty much dead anyway I suppose.` in regards to the attacks? maybe a link or links

**Comment by drewwestrick** [comment]
@netflash 

See the link provided below. Also a search for "openpgp signing attacks" yields plenty of articles on the problem. The gist of the issue is that public keys can be signed by other people's private keys. The goal under normal circumstances is to build a "web" of trust where theoretically someone you trust signs a certificate for someone they trust, so on and so forth (think six degrees of separation). This means theoretically if everyone is acting in good faith you can indirectly trust the certificate of an individual who's key you haven't personally verified.

The weakness comes in due to the fact that there is no upper limit on how many "people" aka private keys can be used to verify a public key on an SKS keyserver. What nefarious parties have done is target some high profile PGP people's public keys and started signing them with random keys over and over again. This bloats their public key "poisoning it" to the point where anyone looking to import or otherwise use their public key risks locking up their software due to OpenPGP not handling keys with tons of verification signatures well.

https://duo.com/decipher/openpgp-certificate-attack-worries-experts

**Comment by mwilck** [comment]
@drewwestrick, exactly. @netflash, see also

 * [LWN: "OpenPGP certificate flooding"](https://lwn.net/Articles/792366/)
 * [R. J. Hansen's Blog: "SKS Keyserver Network under Attack"](https://gist.github.com/rjhansen/67ab921ffb4084c865b3618d6955275f)
 * [Lacatora: "The PGP problem"](https://latacora.micro.blog/2019/07/16/the-pgp-problem.html)

**Comment by mwilck** [comment]
@netflash, wrt the WoT in particular, the main countermeasure that has been taken so far is to ignore 3rd-party signatures on keys imported from keyservers. R. J. Hansen himself has recommended using https://keys.openpgp.org/ instead of the SKS network, and https://keys.openpgp.org doesn't export 3rd-party signatures at all. And late versions of GnuPG ignore 3rd-party signatures by default when importing from keyservers even if the server offers them (`self-sigs-only` option).

Thus, for building up and maintaining the Web of Trust, you're now basically forced to import keys obtained through different means such as e-mail; keyservers don't provide this functionality any more.
