### ISSUE TITLE
Elaborate on why to have seperate keys for signing, encryption and authentication

### ISSUE THREAD

**Issue by mirko** [drduh/YubiKey-Guide#208]
First of all: thanks a lot for this guide!

I think it might be worthwhile to elaborate on the decision not to create "one" sub-key with all capabilities but one for signing, encryption and authentication.
Given that PGP is often used for encryption/signing e-mails and according guides/tutorials (for email encryption/signing) usually don't make a difference between the types, the following questions popped up in my mind while reading:
a) what's the reason(s) / benefit(s) this guide goes straight for separate keys for each purpose?
b) how does that go along / interfere with real-world scenarios where I want to use generated keys and potential drawbacks (e.g. as far as I know I can not upload twi different (encryption/signing) keys issued to the same identity to common public key servers)?

Thanks!

**Comment by drduh** [comment]
Subkeys help with identity management. The long-term, offline identity should rarely change, but subordinate keys might may need to rotate at varied frequencies depending on the goals (for example, you might want to rotate your encryption keys often because PGP does not provide forward secrecy, but keep your authentication key for SSH longer-term). The guide errs on the side of being too defensive than not in this regard, but certainly you're welcome to propose alternative identity management and subkey practices in a PR.

**Comment by drduh** [comment]
Send a PR if you'd like to document this in the guide, otherwise readers can search past Issues.
