### ISSUE TITLE
Update scdaemon.conf for gnupg 2.3 with MacOS (and possibly others)

### ISSUE THREAD

**Issue by oursland** [drduh/YubiKey-Guide#256]
gnupg 2.3.x has broken interaction with Yubikeys and possibly other smart cards on MacOS (and possibly other systems).  A workaround has been noted on the related Homebrew [hombrew-core issue](https://github.com/Homebrew/homebrew-core/pull/75755#issuecomment-825381930).

Documentation should be updated to reflect this fix to ensure proper interaction with smart cards with gnupg 2.3.x.

**Comment by mileslauridsen** [comment]
Just a note, the workaround in the link doesn't appear to work on OSX Catalina.

**Comment by lbogdan** [comment]
@mileslauridsen It works for me - macOS Catalina 10.15.7.

**Comment by jasonkarns** [comment]
For anyone who's willing and able: homebrew is [open to the idea](https://github.com/Homebrew/homebrew-core/pull/75755#issuecomment-840681697) of having the gnupg formula itself write the `disable-ccid` directive to the scdaemon.conf file during installation

**Comment by Paraphraser** [comment]
Just to add a small note - the only mention of `scdaemon.conf` in the guide is under Windows. When my YubiKey stopped working after `brew upgrade` and I found my way here, then onto the link mentioned above and the discussion of `scdaemon.conf`, I found that I didn't have such a file on any of my Macs (a mixture of High Sierra, Mojave and Catalina). That was *slightly* puzzling because all the advice was written in a way which suggested the file should already be there.

I created it anyway but I found I had to add two lines to get it to work:

```
pcsc-driver /System/Library/Frameworks/PCSC.framework/PCSC
disable-ccid
```

People who know more than I do have been at pains to assure me that the first line is the default and is unnecessary but my YubiKey did not start working again until I added that line.

The whole thing is weird.

**Comment by jasonkarns** [comment]
FYI, PR is open to the homebrew formula so manual configuration shouldn't be necessary for homebrew installations much longer: https://github.com/Homebrew/homebrew-core/pull/77606

**Comment by drduh** [comment]
Resolving for now. Please send a PR if a documentation update is still needed.

**Comment by dragon788** [comment]
I didn't need the path to pcsc-driver, but I *DID* need the `disable-ccid` in this file. I was very confused because it had been working on Big Sur for quite a while, but I recently did a `brew upgrade` and must've pulled in the newer GPG finally.

**Comment by dragon788** [comment]
Also of note @drduh is that the brew MR has been blocked pending a reviewer, so updating the docs/example to add `disable-ccid` at the very least is probably worthwhile.

**Comment by dragon788** [comment]
See also a semi-definitive note that the `pcsc-driver` line probably isn't necessary, https://github.com/Homebrew/homebrew-core/pull/75755#issuecomment-839689458
