### ISSUE TITLE
Getting issue `Hi <my github id>! You've successfully authenticated, but GitHub does not provide shell access.`

### ISSUE THREAD

**Issue by ayushmishra2005** [drduh/YubiKey-Guide#344]
I am getting below message while hitting this step https://github.com/drduh/YubiKey-Guide#connect-with-public-key-authentication

`Hi <my github id>! You've successfully authenticated, but GitHub does not provide shell access.`

Please let me know if I am missing any step.

**Comment by sudaraka** [comment]
This is expected behavior, although it doesn't show the exact message in there. That particular `ssh` command only suppose to verify that your public key authentication works. So AFAIS you are on the correct path.

**Comment by iandstanley** [comment]
This command is just to test an ssh connection  GitHub does not give a shell but rather an api over the ssh connection. Once you have tested that the connection does fail with connection refused you should be able to git clone via sshSent from my iPhoneOn 9 Oct 2022, at 16:37, Sudaraka Wijesinghe ***@***.***> wrote:﻿
This is expected behavior, although it doesn't show the exact message in there. That particular ssh command only suppose to verify that your public key authentication works. So AFAIS you are on the correct path.
