### ISSUE TITLE
Corporate RootCA for signing?

### ISSUE THREAD

**Issue by knaggit** [drduh/YubiKey-Guide#358]
Hey there,
did someone create something like a root CA and creating several keys for people like software engineers?
I am in a situation where I generating keys on a air gapped device to configure these on yubikeys for several people. Wouldn't it make sense to sign it with a root CA? To i.e. trust keys from others automatically because CA is trusted?

**Comment by Paraphraser** [comment]
I'm kinda interested in this scenario too. I haven't figured out the answer so I'm a definite +1 on this issue.

**Comment by sp8c3** [comment]
Hi, 
a root-ca as well as what you would call a traditional certificate authority in general does not exist for GPG, which is exclusively discussed in the guide, because GPG is based on the so-called [Web of Trust](https://en.wikipedia.org/wiki/Web_of_trust) model.
A workaround would be to have a key that everyone trusts and that can sign the other keys.
I did a quick google search and found [this](https://gitlab.com/openpgp-ca/openpgp-ca), which should roughly cover your use case.

**Comment by smlx** [comment]
SSH supports the trusted CA model. You could use the PIV app on the Yubikey (as opposed to the PGP app) to handle certificates.

https://developers.yubico.com/PIV/

**Comment by knaggit** [comment]
Hey,
thank you very much for your answers! Helped me to decide whether X.509 or PGP is valuable for the organization (especially because it's a tech company).
Would be still interesting how the workflow would be, if you are in charge for a few people to issue their PGP keys (even when you give them a private keys later and don't keep any information). Unfortunately the entire topic isn't easily learnt by a day and much less if you're not interested in that stuff. So it is a realistic scenario in my opinion, that I need to issue some keys for people. Of course it's maybe not the scope of this guide.
Happy holidays!
