### ISSUE TITLE
Can't make commits after losing yubikey

### ISSUE THREAD

**Issue by AHuntress** [drduh/YubiKey-Guide#364]
Hi there,

I'm not a dev but I use git to update content strings, authorized by yubikey. Which I lost. I have a new one linked to my github account, but if I try to make commits, it's still asking for the old, lost one. It seems this has stumped everyone in IT at Shopify. I've also scoured (and not understood) any of the github documentation around GPG and SSh keys. Please help! I want to remove any associated authorizations with yubikey on my account. 

Thanks in advance!

**Comment by Paraphraser** [comment]
Have you tried the first command at [using-multiple-keys](https://github.com/drduh/YubiKey-Guide#using-multiple-keys)?

I have two YubiKeys, programmed alike. If I use key A on a machine for any gpg operation (like signing a commit), and then I try to use key B on that machine, I will always get prompted to insert key A until I run that "learn --force" command, after which key B works just fine ... until I switch back to key A. Rinse, repeat.

I think a "replacement key" (your situation) is similar: your host knows about your old key and you have to force it to learn your new key. Give it a try.

**Comment by iandstanley** [comment]
Without seeing the output I'm not 100% sure what you are asking. 

If you mean that you are afraid that the lost key could be used to fake commits on your behalf then thereafter the following 

What key are you using to SSH into GitHub ?  

Did you generate the key with SSH's keygen command or are you using a GPG key to ssh 

If it is a key generated with SSH then you should simply go into your security settings and remove the key. As ssh-keygen can't put identical keys on two separate Yubikeys (because they are generated on the Yubikey itself) simply removing the key from GitHub's settings is sufficient 

If it is a GPG key then it's a little more complicated. 

With a GPG key we are  talking either signed commits or ssh with GPG keys. 

For signed commits you will need to change your signing key in your gut config file. 

For ssh with GPG  keys it’s is more detailed     

If you have a single GPG key on two Yubikeys then you MUST revoke your old key, regenerate and add the new key to your Yubikey.  You cannot block the key on the lost Yubikey whilst continuing to use the same key in a second Yubikey. 

Also you should delete the OLD Yubikey public key from GitHub’s settings and add the new one. 

If however you the key you have lost had the only copy of the private key then revoke that key and delete from GitHub and then add you new key.

**Comment by AHuntress** [comment]
Hi Phil,

I ran that first command and got this output:
[image: image.png]

Ian, sorry, I don't understand any of your questions (I'm not a developer).
As far as I know, I have no SSH or GPG keys on my github account. It's an
actual yubikey that I needed to insert to make commits. I'm not worried
about it falling into the wrong hands, just that I can't make commits with
the new one, which is on my github account. Does that make sense?

A.

*Alexandra Hunter*
Staff Marketing Content Designer | Shopify
Victoria, BC, Canada (PT)

Slack: @alexandra.hunter
Canada cell: +1 236 562 8357
Mexico cell: +52 415 144 2599

**Comment by Paraphraser** [comment]
Hi Alexandra,

I've definitely heard your "not a developer". I'm not a "security guru", just a user of this stuff and I get stymied a fair bit too.

I will include some technical detail in case you decide to ask for help from the tech support people at Shopify.

First off, your "image.png" didn't make it into the issue. I'm not sure how you added it. In my browser the bottom part of the comment box says "Attach files by dragging & dropping, selecting or pasting them." That text is also a live link you can click, get a dialog window, select the image, and upload it. I mostly use drag and drop. What I usually do too is click the "Preview" tab at the top of the comment box. If I can't see an uploaded file in the preview, that usually means it didn't work so I go back and try again.

<hr>

Rather than wait for you to try to add the image again, I thought I might try to replicate what I *think* is your problem so you can tell me if you see something similar.

What was interesting about my attempt to replicate is that I was unable to do it on macOS. In the past I've definitely had to muck around when swapping YubiKeys on macOS so I'm not entirely sure why I don't have to do it any more. It *may* be related to the GnuPG version I'm running on macOS which is 2.3.8.

However, I **was** successful replicating the problem on Linux where the GnuPG version is 2.2.27.

> To be specific (thinking "Shopify tech support" here), my test machine is a Raspberry Pi running Raspberry Pi OS Debian Bullseye, where I let `apt` do all the work of keeping installed packages up-to-date. In other words, I haven't installed a specific version of GnuPG, just used whatever is provided for the operating system by default.
> 
> I also looked at a recent vanilla Debian install on an Intel box. That was also 2.2.27. That's another way of saying that it seems to me - assumption, no hard evidence - that 2.2.27 is probably fairly common, at least for Debian. I can't say about Windows or other flavours of Linux.

Anyway, here we go:

```
4GB Raspberry Pi 4 Model B Rev 1.1 running Debian GNU/Linux 11 (bullseye) as full 64-bit OS

$ gpg --version
gpg (GnuPG) 2.2.27
…
```

What YubiKey is in the slot?

```
$ gpg --card-status
Reader ...........: Yubico YubiKey OTP FIDO CCID 00 00
Application type .: OpenPGP
Version ..........: 3.4
Manufacturer .....: Yubico
Serial number ....: 21449967
```

Let's make a test directory, stick a file in it, then initialise that as a Git repository:

```
$ mkdir test
$ ls -l >test/file.txt
$ cd test
$ git init
…
```

Now I'll tell Git to add that file and commit with signing:

```
$ git add file.txt 
pi@sec-dev:~/test$ git commit -m "first commit" -s -S
[master (root-commit) ef76393] first commit
 1 file changed, 18 insertions(+)
 create mode 100644 file.txt
```

I was prompted for the YubiKey PIN and then had to touch the YubiKey but it "just worked".

Now I'll move the goal-posts by removing the YubiKey with serial number 21449967 and replace it with a different YubiKey with serial number 10946422. Both YubiKeys have been "programmed alike" so they have exactly the same private keys stored on them. The YubiKey are **intended** to be interchangeable.

```
$ gpg --card-status
Reader ...........: Yubico YubiKey OTP FIDO CCID 00 00
Application type .: OpenPGP
Version ..........: 3.4
Manufacturer .....: Yubico
Serial number ....: 10946422
…
```

I'll add another file to this directory (I'm just `tree` to generate a file), then I'll add and commit that with signing:

```
$ tree . >tree.txt
$ git add tree.txt 
$ git commit -m "second" -s -S
error: gpg failed to sign the data
fatal: failed to write commit object
```

What happened was I got this prompt:

```
┌─────────────────────────────────────────────┐
│ Please insert the card with serial number:  │
│                                             │
│ 0006 21449967                               │
│                                             │
│      <OK>                       <Cancel>    │
└─────────────────────────────────────────────┘
``` 

That's asking for the first YubiKey.

Pressing OK didn't get anywhere. It just re-displayed the same prompt. I clicked CANCEL and that's what caused the "failed to sign" message above.

So, now I tell GnuPG to forget about the first YubiKey, in favour of the second YubiKey which is in the USB port:

```
$ gpg-connect-agent "scd serialno" "learn --force" /bye
S SERIALNO …
OK
S PROGRESS learncard k 0 0
S PROGRESS learncard k 0 0
S PROGRESS learncard k 0 0
OK
```

Then I repeat the attempt to commit with signing:

```
$ git commit -m "second" -s -S
[master a5c0087] second
 1 file changed, 5 insertions(+)
 create mode 100644 tree.txt
```

I get prompted for the YubiKey's PIN, then touch the key, and the commit succeeds.

When you say "… still asking for the old, lost one" it sounds to me very much like this problem. What do you think? Plausible?

**Comment by AHuntress** [comment]
Hi Ian!

My dev friend found the solution (how to reverse needing a yubikey to make
commits):

git config --global --unset user.signingkey
git config --global commit.gpgsign false

*Alexandra Hunter*
Staff Marketing Content Designer | Shopify
Victoria, BC, Canada (PT)

Slack: @alexandra.hunter
Canada cell: +1 236 562 8357
Mexico cell: +52 415 144 2599

**Comment by drduh** [comment]
Thank you @Paraphraser and @iandstanley for the community support! Much appreciated!
