### ISSUE TITLE
Private keys exportable

### ISSUE THREAD

**Issue by materia-nigra** [drduh/YubiKey-Guide#410]
I've followed this wonderful guide on how to use GPG with YubiKey. After completing all the steps, I tried to export the private keys with `gpg --export-secret-keys --armor --output private.gpg <my-id>` and the command was successfull. Aren't the private keys "unexportable", since they reside on the YubiKey? I'm no security expert, so I know I'm missing something obvious.

**Comment by iandstanley** [comment]
It exports a stub pointing to a particular Yubikey On 5 Jan 2024, at 22:22, materia-nigra ***@***.***> wrote:﻿
I've followed this wonderful guide on how to use GPG with YubiKey. After completing all the steps, I tried to export the private keys with gpg --export-secret-keys --armor --output private.gpg <my-id> and the command was successfull. Aren't the private keys "unexportable", since they reside on the YubiKey? I'm no security expert, so pardon if I'm missing something obvious.

**Comment by leohidalgo** [comment]
You must follow the order of the guide, first you export the public key, make the backup on your removable device and finally you transfer your keys to the Yubikey, in the guide it says:

```
**Important** Transferring keys to YubiKey using keytocard is a destructive, one-way operation only. Make sure you've made a backup before proceeding: keytocard converts the local, on-disk key into a stub, which means the on-disk copy is no longer usable to transfer to subsequent security key devices or mint additional keys. 
```
