### ISSUE TITLE
Multiple hosts section removal

### ISSUE THREAD

**Issue by laurazard** [drduh/YubiKey-Guide#432]
The `Multiple Hosts` section was removed in https://github.com/drduh/YubiKey-Guide/commit/d6848d544037bac5726a958d4425325a248e4e67, which was merged from https://github.com/drduh/YubiKey-Guide/pull/417. Neither the commit removing the section or the merge request in which it was included have any text explaining the rationale for which it was removed, which is terrible practice in a living guide such as this.

As someone who's relied on this guide for guidance in the past, coming back to find a section that describes something you were using missing, with no explanation, I'm left wondering whether it was removed because it was unsafe and I should do a security assessment, because it was bad practice, or because the author personally disliked it.

In the future, can we document these changes somewhere? Even if not on any kind of "changelog", explaining the reason why a change such as this was made in the commit that introduces that change would inspire a lot more trust.

**Comment by laurazard** [comment]
Nevermind, I should get some sleep 😅 Found the new "multiple computers" section in "Notes".

**Comment by drduh** [comment]
Sorry about that @laurazard - I also hate it when changes are made without details.

The guide got a big overhaul recently and some stuff got shifted around to reduce steps and time. Let me know if anything else was missed! We will also continue posting any known or discovered security issues at the top of the guide for a relevant amount of time.

**Comment by Speeddymon** [comment]
Hello, one item was missed. When "Multiple Hosts" was renamed, not only should [this page in the Yubico docs](https://support.yubico.com/hc/en-us/articles/360013790259-Using-Your-YubiKey-with-OpenPGP) have the below section updated to mention to look at the Notes section here, but also the link should be updated to point to the Notes section.

> ## Using your YubiKey's OpenPGP function on multiple computers
>
> In order to use the OpenPGP private keys stored on your YubiKey on computers apart from the one where they were generated, it is necessary to import the corresponding public keys. Please see [this guide](https://github.com/drduh/YubiKey-Guide#multiple-hosts) (under the section Multiple Hosts) for more information.

I'm not sure if you have any sway with Yubico, but since they are linking to your content, I figured you might want to reach out and let them know of the issue.
