### ISSUE TITLE
doas command missing when exporting public key (nixos)

### ISSUE THREAD

**Issue by mairs8** [drduh/YubiKey-Guide#443]
i am using the nixos live image. 

when i try to run the below i get an error `doas: command not found`. 

```
gpg --armor --export $KEYID | doas tee /mnt/public/$KEYID-$(date +%F).asc
```

looks like doas is not installed as part of the environment. is there something i am missing?

**Comment by Paraphraser** [comment]
See [How to Install and Use doas](https://www.makeuseof.com/how-to-install-and-use-doas/). I've never used `doas` myself so I can't speak to its efficacy.

Were I to be following the Dr Duh guide and encountered a command containing `doas`, I'd just substitute `sudo` and get on with my life.

As an aside, it's a while since I set up my own YubiKeys so I haven't really been paying ultra-close attention to changes and hadn't noticed `doas` creeping in. Use of `doas` always seems to be under an "OpenBSD" heading and that, combined with the fact that it isn't mentioned as a dependency at [install-software](https://github.com/drduh/YubiKey-Guide#install-software) makes me think `doas` is always available on OpenBSD systems (or, at least, the author of those sections of the guide *believes* that to be the case).

Are you using OpenBSD? If you are and `doas` isn't there by default then I think you should mention that so it can either be added as a dependency or the pros/cons of `doas` vs `sudo` discussed.

**Comment by drduh** [comment]
Looks like you may be following instructions for OpenBSD. Those are around to encourage system diversity to Linux. Let us know if we can make the distinction clearer in any way.
